version: 2

defaults: &defaults
  working_directory: ~/formless
  docker:
    - image: thomashoneyman/purescript:0.0.3

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

  docs:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages

      # On master branch, rebuild documentation site
      - docs:
          filters:
            branches:
              only: master

          requires:
            - test

